### Import Pakages

In [36]:
# For building neural networks.
import keras as kr

# For interacting with data sets.
import pandas as pd

# For encoding categorical variables.
import sklearn.preprocessing as pre

# For splitting into training and test datasets.
import sklearn.model_selection as mod

### Import Data

In [37]:
#Add heading to csv file
headings = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
#Read in data from a csv file
df = pd.read_csv('housing.csv',delim_whitespace=True,names = headings) 
#Print first 5 lines of imported data 
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [38]:
inputs = df.drop(columns =['MEDV'])
outputs = df[['MEDV']]

## Create model

In [93]:
# Start a neural network, building it by layers.
model = kr.models.Sequential()

# Add a hidden layer with x neurons and an input layer with 4.
model.add(kr.layers.Dense(units=13, activation='relu', input_dim=13))
# Add a three neuron output layer.
model.add(kr.layers.Dense(units=1, activation='relu'))

# Build the graph.
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [94]:
## Summary of the sequential model
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_13 (Dense)             (None, 13)                182
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 14
=================================================================
Total params: 196
Trainable params: 196
Non-trainable params: 0
_________________________________________________________________

### Split into training and test data

In [67]:
from sklearn.model_selection import train_test_split
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
415,18.08460,0.0,18.10,0,0.679,6.434,100.0,1.8347,24,666.0,20.2,27.25,29.05
219,0.11425,0.0,13.89,1,0.550,6.373,92.4,3.3633,5,276.0,16.4,393.74,10.50
226,0.38214,0.0,6.20,0,0.504,8.040,86.5,3.2157,8,307.0,17.4,387.38,3.13
152,1.12658,0.0,19.58,1,0.871,5.012,88.0,1.6102,5,403.0,14.7,343.28,12.12
275,0.09604,40.0,6.41,0,0.447,6.854,42.8,4.2673,4,254.0,17.6,396.90,2.98

In [74]:
print(inputs_train)
#outputs_train.head()

         CRIM    ZN  INDUS  CHAS     NOX     RM    AGE     DIS  RAD    TAX  \
415  18.08460   0.0  18.10     0  0.6790  6.434  100.0  1.8347   24  666.0
219   0.11425   0.0  13.89     1  0.5500  6.373   92.4  3.3633    5  276.0
226   0.38214   0.0   6.20     0  0.5040  8.040   86.5  3.2157    8  307.0
152   1.12658   0.0  19.58     1  0.8710  5.012   88.0  1.6102    5  403.0
275   0.09604  40.0   6.41     0  0.4470  6.854   42.8  4.2673    4  254.0
288   0.04590  52.5   5.32     0  0.4050  6.315   45.6  7.3172    6  293.0
493   0.17331   0.0   9.69     0  0.5850  5.707   54.0  2.3817    6  391.0
25    0.84054   0.0   8.14     0  0.5380  5.599   85.7  4.4546    4  307.0
423   7.05042   0.0  18.10     0  0.6140  6.103   85.1  2.0218   24  666.0
261   0.53412  20.0   3.97     0  0.6470  7.520   89.4  2.1398    5  264.0
169   2.44953   0.0  19.58     0  0.6050  6.402   95.2  2.2625    5  403.0
202   0.02177  82.5   2.03     0  0.4150  7.610   15.7  6.2700    2  348.0
233   0.33147   0.0   6.20     0  0.5070  8.247   70.4  3.6519    8  307.0
502   0.04527   0.0  11.93     0  0.5730  6.120   76.7  2.2875    1  273.0
143   4.09740   0.0  19.58     0  0.8710  5.468  100.0  1.4118    5  403.0
297   0.14103   0.0  13.92     0  0.4370  5.790   58.0  6.3200    4  289.0
167   1.80028   0.0  19.58     0  0.6050  5.877   79.2  2.4259    5  403.0
348   0.01501  80.0   2.01     0  0.4350  6.635   29.7  8.3440    4  280.0
250   0.14030  22.0   5.86     0  0.4310  6.487   13.0  7.3967    7  330.0
346   0.06162   0.0   4.39     0  0.4420  5.898   52.3  8.0136    3  352.0
209   0.43571   0.0  10.59     1  0.4890  5.344  100.0  3.8750    4  277.0
21    0.85204   0.0   8.14     0  0.5380  5.965   89.2  4.0123    4  307.0
60    0.14932  25.0   5.13     0  0.4530  5.741   66.2  7.2254    8  284.0
16    1.05393   0.0   8.14     0  0.5380  5.935   29.3  4.4986    4  307.0
168   2.30040   0.0  19.58     0  0.6050  6.319   96.1  2.1000    5  403.0
447   9.92485   0.0  18.10     0  0.7400  6.251   96.6  2.1980   24  666.0
470   4.34879   0.0  18.10     0  0.5800  6.167   84.0  3.0334   24  666.0
136   0.32264   0.0  21.89     0  0.6240  5.942   93.5  1.9669    4  437.0
161   1.46336   0.0  19.58     0  0.6050  7.489   90.8  1.9709    5  403.0
201   0.03445  82.5   2.03     0  0.4150  6.162   38.4  6.2700    2  348.0
..        ...   ...    ...   ...     ...    ...    ...     ...  ...    ...
474   8.05579   0.0  18.10     0  0.5840  5.427   95.4  2.4298   24  666.0
4     0.06905   0.0   2.18     0  0.4580  7.147   54.2  6.0622    3  222.0
406  20.71620   0.0  18.10     0  0.6590  4.138  100.0  1.1781   24  666.0
204   0.02009  95.0   2.68     0  0.4161  8.034   31.9  5.1180    4  224.0
468  15.57570   0.0  18.10     0  0.5800  5.926   71.0  2.9084   24  666.0
113   0.22212   0.0  10.01     0  0.5470  6.092   95.4  2.5480    6  432.0
150   1.65660   0.0  19.58     0  0.8710  6.122   97.3  1.6180    5  403.0
417  25.94060   0.0  18.10     0  0.6790  5.304   89.1  1.6475   24  666.0
259   0.65665  20.0   3.97     0  0.6470  6.842  100.0  2.0107    5  264.0
488   0.15086   0.0  27.74     0  0.6090  5.454   92.7  1.8209    4  711.0
218   0.11069   0.0  13.89     1  0.5500  5.951   93.8  2.8893    5  276.0
76    0.10153   0.0  12.83     0  0.4370  6.279   74.5  4.0522    5  398.0
29    1.00245   0.0   8.14     0  0.5380  6.674   87.3  4.2390    4  307.0
149   2.73397   0.0  19.58     0  0.8710  5.597   94.9  1.5257    5  403.0
472   3.56868   0.0  18.10     0  0.5800  6.437   75.0  2.8965   24  666.0
48    0.25387   0.0   6.91     0  0.4480  5.399   95.3  5.8700    3  233.0
428   7.36711   0.0  18.10     0  0.6790  6.193   78.1  1.9356   24  666.0
313   0.26938   0.0   9.90     0  0.5440  6.266   82.8  3.2628    4  304.0
215   0.19802   0.0  10.59     0  0.4890  6.182   42.4  3.9454    4  277.0
97    0.12083   0.0   2.89     0  0.4450  8.069   76.0  3.4952    2  276.0
9     0.17004  12.5   7.87     0  0.5240  6.004   85.9  6.5921    5  311.0
2     0.02729   0.0   7.07     0  0.4690  7.185   61.1  4.9671    2  242.0
164   2.24236   0.0  19.58     0  0.6050  5.854   91.8  2.4220    5  403.0
337   0.03041   0.0   5.19     0  0.5150  5.895   59.6  5.6150    5  224.0
185   0.06047   0.0   2.46     0  0.4880  6.153   68.8  3.2797    3  193.0
326   0.30347   0.0   7.38     0  0.4930  6.312   28.9  5.4159    5  287.0
10    0.22489  12.5   7.87     0  0.5240  6.377   94.3  6.3467    5  311.0
35    0.06417   0.0   5.96     0  0.4990  5.933   68.2  3.3603    5  279.0
268   0.54050  20.0   3.97     0  0.5750  7.470   52.6  2.8720    5  264.0
87    0.07151   0.0   4.49     0  0.4490  6.121   56.8  3.7476    3  247.0

     PTRATIO       B  LSTAT
415     20.2   27.25  29.05
219     16.4  393.74  10.50
226     17.4  387.38   3.13
152     14.7  343.28  12.12
275     17.6  396.90   2.98
288     16.6  396.90   7.60
493     19.2  396.90  12.01
25      21.0  303.42  16.51
423     20.2    2.52  23.29
261     13.0  388.37   7.26
169     14.7  330.04  11.32
202     14.7  395.38   3.11
233     17.4  378.95   3.95
502     21.0  396.90   9.08
143     14.7  396.90  26.42
297     16.0  396.90  15.84
167     14.7  227.61  12.14
348     17.0  390.94   5.99
250     19.1  396.28   5.90
346     18.8  364.61  12.67
209     18.6  396.90  23.09
21      21.0  392.53  13.83
60      19.7  395.11  13.15
16      21.0  386.85   6.58
168     14.7  297.09  11.10
447     20.2  388.52  16.44
470     20.2  396.90  16.29
136     21.2  378.25  16.90
161     14.7  374.43   1.73
201     14.7  393.77   7.43
..       ...     ...    ...
474     20.2  352.58  18.14
4       18.7  396.90   5.33
406     20.2  370.22  23.34
204     14.7  390.55   2.88
468     20.2  368.74  18.13
113     17.8  396.90  17.09
150     14.7  372.80  14.10
417     20.2  127.36  26.64
259     13.0  391.93   6.90
488     20.1  395.09  18.06
218     16.4  396.90  17.92
76      18.7  373.66  11.97
29      21.0  380.23  11.98
149     14.7  351.85  21.45
472     20.2  393.37  14.36
48      17.9  396.90  30.81
428     20.2   96.73  21.52
313     18.4  393.39   7.90
215     18.6  393.63   9.47
97      18.0  396.90   4.21
9       15.2  386.71  17.10
2       17.8  392.83   4.03
164     14.7  395.11  11.64
337     20.2  394.81  10.56
185     17.8  387.11  13.15
326     19.6  396.90   6.15
10      15.2  392.52  20.45
35      19.2  396.90   9.68
268     13.0  390.30   3.16
87      18.5  395.15   8.44

[404 rows x 13 columns]

In [83]:
inputs_test.iloc[0,:]

CRIM         0.15936
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           6.21100
AGE          6.50000
DIS          5.72090
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          394.46000
LSTAT        7.44000
Name: 43, dtype: float64

In [85]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\Harvey Norman\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

array([[1.]], dtype=float32)

In [91]:
#model.fit(inputs_train, outputs_train, epochs=15, batch_size=10)
from keras.wrappers.scikit_learn import KerasRegressor
estimator = KerasRegressor(build_fn=model, epochs=15, batch_size=10)

In [43]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\Harvey Norman\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

array([[1.]], dtype=float32)

In [46]:
# Have the network predict the classes of the test inputs.
predictions = model.predict(inputs_test)
print(predictions)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]